[package]
name = "bincode_compatibility"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "./README.md"
description = "Internal compatibility tests for bincode"
publish = false

[dependencies]
bincode = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }
